### ISSUE TITLE
Error adding entities for domain sensor with platform linksys_velop

### ISSUE THREAD

**Issue by Warble68** [uvjim/linksys_velop#23] opened 2021-10-11 01:39 UTC
Maybe this issue is because my router is a Linksys AC2200 Smart Mesh Wi-Fi Router (model: MR8300v1, firmware: 1.1.8.203202) and it has a child Linksys Velop Mesh Router (model: WHW03Bv2, firmware: 2.1.18.206964) used to expand my Wi-Fi coverage.
It does the device tracker wonderfully, which is what I mostly wanted.  Just thought I would share about these errors.
I get this error after each restart.

Logger: homeassistant.components.sensor
Source: custom_components/linksys_velop/entity_helpers.py:79
Integration: Sensor (documentation, issues)
First occurred: 8:15:11 PM (2 occurrences)
Last logged: 8:15:11 PM

Error adding entities for domain sensor with platform linksys_velop
Error while setting up linksys_velop platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 457, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/linksys_velop/entity_helpers.py", line 79, in device_info
    "sw_version": node.firmware.get("version", ""),
  File "/usr/local/lib/python3.9/site-packages/pyvelop/base.py", line 29, in __getattribute__
    ret = object.__getattribute__(self, item)
  File "/usr/local/lib/python3.9/site-packages/pyvelop/node.py", line 46, in firmware
    available_updates = self.__attributes.get("updates", {}).get("availableUpdate", {})
AttributeError: 'list' object has no attribute 'get'

**Comment by uvjim** [comment] 2021-10-18 18:25
Hi,

I have a feeling I know what the issue is.  However, if I give you the request that I use would you be able to run it against your router, using Postman, and share the results please?

**Comment by uvjim** [comment] 2022-01-24 14:32
Should be fixed in #60

**Closed by uvjim** 2022-01-24 14:33 UTC
Labels: question, upstream
