### ISSUE TITLE
Error after Homeassistant OS 14

### ISSUE THREAD

**Issue by DjMayone** [uvjim/linksys_velop#545] opened 2024-12-07 08:33 UTC
Hi, after updating to HomeAssistant OS 14 the integration stopped working with error: " Setup failed for custom integration 'linksys_velop': Unable to import component: cannot import name 'entity_registry' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)"

**Comment by uvjim** [comment] 2024-12-07 08:42
Duplicate of #522 and #541.

Please ensure you're running at least `2024.12.1` of this integration.

**Closed** 2024-12-07 08:42 UTC
