### ISSUE TITLE
Linksys Velop: Reboot Node Service Not working

### ISSUE THREAD

**Issue by aAbdman** [uvjim/linksys_velop#230] opened 2022-08-01 21:10 UTC
Hello

In the beta version [2022.8.1b0 and 2022.8.1b0] the (Linksys Velop: Reboot Node) in not woking anymore.

**Comment by uvjim** [comment] 2022-08-01 21:31
Are there any errors in the logs at all?

**Comment by uvjim** [comment] 2022-08-01 21:55
I know what the issue is. It's late here so I'll deal with it tomorrow.

**Comment by uvjim** [comment] 2022-08-02 08:17
Should be fixed in #231

**Closed by uvjim** 2022-08-02 08:17 UTC
Labels: bug

**Comment by aAbdman** [comment] 2022-08-02 14:14
Yes, it works good now.
Thank you
